# argument to provide specific version of shido node
ARG INITIAL_VERSION
FROM tharsishq/shido:$INITIAL_VERSION

WORKDIR /go/src/github.com/shido/shido

COPY ./init-node.sh .

# JSON-RPC server
EXPOSE 8545

CMD ["sh", "./init-node.sh"]
